#!/usr/bin/env python3
"""Timur C software tests (Phase 12): build, run on the reference model, write the vectors.

Builds every program in sw/tests/ for rv32im_zicsr and rv32imc_zicsr with the
runtime (sw/build.py), runs each image on the reference model with interrupts
and the console input modelled, checks the result, and writes, relative to the
project root:
  vectors/timur_sw_<name>_<isa>.hex   ROM image, 32-bit words, symbols as comments
  vectors/timur_sw_<name>_<isa>.out   UART output of the model: what tb/timur_sw_tb.v expects
  vectors/timur_sw_<name>.in          UART input, for programs that read the console
  vectors/timur_sw_vectors.txt        programs and checks for tb/timur_sw_tb.v

The model sends UART bytes at once and copies DMA blocks at once, so it takes
interrupts earlier than the SoC does; the programs print nothing that depends
on timing, which is why their output must match the SoC's byte for byte. The
generator also checks that the two builds print the same text (the traps test
up to its final report, which shows a code address) and that each program's
own checks passed on the model.

Without the toolchain the committed images are read back, so the expectations
can still be regenerated. Usage:  python3 sw/gen_sw_tests.py [--root DIR]
"""

from __future__ import annotations

import argparse
import logging
import sys
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from timur_tools import builder, cli, memmap, paths, romimage
from timur_tools.errors import GenerationError
from timur_tools.model import ModelError, TimurModel
from timur_tools.paths import Project
from timur_tools.toolchain import PINNED_GCC_VERSION, Toolchain, find_toolchain
from timur_tools.vectors import Vectors, prog_cycle_budget

LOG = logging.getLogger("timur.gen_sw_tests")

ISAS = ("rv32im_zicsr", "rv32imc_zicsr")
UART_CYCLES_PER_BIT = memmap.TB_SW_UART_CYCLES_PER_BIT
#: Symbols recorded in the image files: the testbench needs _halt, a reader the rest.
SYMBOLS = ("_start", "_halt", "trap_entry", "main", "_end", "_heap_end", "_stack_top")
#: Words the test programs print when one of their own checks fails.
FAILURE_WORDS = ("MISMATCH", "DIFFER", "WRONG", "not reached", "FAIL")
MODEL_LIMIT = 50_000_000  # instructions
VECTOR_FILE = paths.VECTORS + "/timur_sw_vectors.txt"
VECTOR_FILE_HELP = (
    """\
timur_sw test vectors, generated by sw/gen_sw_tests.py: the C programs of Phase 12
on tb/timur_sw_tb.v (timur_soc_tb with a UART of %d cycles per bit).
Directives as in vectors/timur_soc_vectors.txt, and:
  UARTIN <file>    bytes sent on uart_rx during the next PROG, each once the receiver is
                   enabled and holds no unread byte; the PROG also checks that all were read
  UARTTEXT <file>  the bytes decoded from uart_tx equal the file (the model's output)
PROG halts at _halt, the jump-to-self that _exit ends in; LEDS is 0x200 | the exit code.
"""
    % UART_CYCLES_PER_BIT
)


@dataclass(frozen=True)
class SwTest:
    """A program in sw/tests/ and what its run must show."""

    name: str
    covers: str
    console_input: bytes
    must_print: tuple[str, ...]
    leds: int  # 0x200 | exit code
    differ_after: str | None  # text after which the two builds may print different things
    hready_waits: bool  # also run it with HREADY wait states


TESTS = (
    SwTest(
        "hello", "printf, a CSR read, the switches", b"",
        ("Hello from Timur RV32IMC!", "misa 40001104: RV32IMC"), 0x200, None, False,
    ),
    SwTest(
        "selftest",
        "globals and sections, stack and recursion, arithmetic including division by zero, "
        "the C library, the heap up to exhaustion, ECALL system calls, CSRs",
        b"", ("checks passed",), 0x200, None, True,
    ),
    SwTest(
        "traps",
        "exceptions handled by the program (illegal instruction, EBREAK, misaligned loads and "
        "stores, 16- and 32-bit), then the runtime's report of an unhandled one",
        b"",
        ("10 exceptions handled;", "reaches the system calls: yes",
         "*** unhandled trap: illegal instruction"),
        0x302, "*** unhandled trap", False,
    ),
    SwTest(
        "io",
        "console input with fgets, sscanf and getchar; DMA done interrupt, a masked interrupt "
        "taken once MIE is set, UART receive interrupt",
        b"12 -30\rTimur\rstressed\rinterrupts work\r",
        ("copied from ROM to RAM correctly", "mip.MEIP = 1", "copy correct",
         "16 bytes, 16 receive interrupts"),
        0x200, None, False,
    ),
)  # fmt: skip


def isa_tag(isa: str) -> str:
    """'rv32imc_zicsr' -> 'rv32imc', as used in file names."""
    return isa.split("_")[0]


def image_name(name: str, isa: str) -> str:
    """Root-relative name of a program's ROM image."""
    return "%s/timur_sw_%s_%s.hex" % (paths.VECTORS, name, isa_tag(isa))


def output_name(name: str, isa: str) -> str:
    """Root-relative name of a program's expected UART output."""
    return "%s/timur_sw_%s_%s.out" % (paths.VECTORS, name, isa_tag(isa))


def input_name(name: str) -> str:
    """Root-relative name of a program's console input."""
    return "%s/timur_sw_%s.in" % (paths.VECTORS, name)


def build_image(
    project: Project, toolchain: Toolchain | None, name: str, isa: str
) -> romimage.HexImage:
    """Build sw/tests/<name>.c and write its image file; without the toolchain,
    read the committed image back."""
    path = project.path(image_name(name, isa))
    if toolchain is None:
        return romimage.read_word_hex(path)
    with tempfile.TemporaryDirectory() as tmp:
        result = builder.build(
            [project.tests / (name + ".c")], isa, Path(tmp), name,
            project=project, toolchain=toolchain,
        )  # fmt: skip
    symbols = {symbol: result.symbol(symbol) for symbol in SYMBOLS}
    lines = [
        "// %s (%s): sw/tests/%s.c with the runtime, built by sw/build.py, %d bytes"
        % (name, isa, name, result.size_bytes)
    ]
    lines += ["// symbol %s %08X" % (symbol, symbols[symbol]) for symbol in SYMBOLS]
    lines += ["%08X" % word for word in result.words]
    romimage.write_lines(path, lines)
    return romimage.HexImage(result.words, symbols)


def run_on_model(test: SwTest, isa: str, image: romimage.HexImage) -> TimurModel:
    """Run an image with the test's console input; the run must pass its checks."""
    label = "%s (%s)" % (test.name, isa)
    model = TimurModel(image.memory(), uart_rx=test.console_input, interrupts=True, trace=False)
    try:
        model.run(MODEL_LIMIT)
    except ModelError as error:
        raise GenerationError("model: %s: %s" % (label, error)) from error
    text = bytes(model.uart_tx).decode("ascii", errors="backslashreplace")
    halt = image.tags.get("_halt")
    if model.pc != halt:
        raise GenerationError("model: %s stopped at %08X, not at _halt" % (label, model.pc))
    if model.uart_rx or model.rx_valid:
        raise GenerationError("model: %s left console input unread" % label)
    for expected in test.must_print:
        if expected not in text:
            raise GenerationError("model: %s output lacks %r:\n%s" % (label, expected, text))
    for word in FAILURE_WORDS:
        if word in text:
            raise GenerationError("model: %s output contains %r:\n%s" % (label, word, text))
    if model.gpio_out != test.leds:
        raise GenerationError(
            "model: %s ends with LEDs %03X, expected %03X" % (label, model.gpio_out, test.leds)
        )
    return model


def check_builds_agree(test: SwTest, outputs: dict[str, bytes]) -> None:
    """Both builds of a program print the same text (up to test.differ_after)."""
    first, second = (outputs[isa] for isa in ISAS)
    if test.differ_after:
        marker = test.differ_after.encode()
        first, second = first.split(marker)[0], second.split(marker)[0]
    if first != second:
        raise GenerationError("model: %s prints different text for %s and %s" % (test.name, *ISAS))


def add_header(vec: Vectors) -> None:
    """The description of the file format."""
    for line in VECTOR_FILE_HELP.splitlines():
        vec.comment(line)
    vec.comment("")


def generate(project: Project, toolchain: Toolchain | None) -> list[str]:
    """Build, run and check every test; write the vectors. Returns a summary line per run."""
    if toolchain is None:
        LOG.info("no toolchain: reusing the committed images in %s/", paths.VECTORS)
    else:
        version = toolchain.gcc_version()
        if version != PINNED_GCC_VERSION:
            LOG.warning(
                "riscv-none-elf-gcc %s: the committed images were built with %s, "
                "so they will change",
                version,
                PINNED_GCC_VERSION,
            )
    vec = Vectors()
    add_header(vec)
    summary = []
    for test in TESTS:
        if test.console_input:
            project.path(input_name(test.name)).write_bytes(test.console_input)
        outputs = {}
        for isa in ISAS:
            image = build_image(project, toolchain, test.name, isa)
            model = run_on_model(test, isa, image)
            out = bytes(model.uart_tx)
            outputs[isa] = out
            project.path(output_name(test.name, isa)).write_bytes(out)
            cycles = prog_cycle_budget(
                model.retired, len(out), len(test.console_input), UART_CYCLES_PER_BIT
            )
            for with_waits in (0, 1) if test.hready_waits else (0,):
                vec.comment(
                    "==== %s (%s)%s: %s; %d instructions on the model, %d UART bytes"
                    % (test.name, isa, ", HREADY waits" if with_waits else "", test.covers,
                       model.retired, len(out))
                )  # fmt: skip
                if test.console_input:
                    vec.add("UARTIN " + input_name(test.name))
                vec.prog(image_name(test.name, isa), cycles, image.tags["_halt"], with_waits)
                vec.add("UARTTEXT " + output_name(test.name, isa))
                vec.add("LEDS %03X" % model.gpio_out)
                vec.add("DIVS %d" % model.divs)
            summary.append(
                "%-9s %-14s %6d bytes of ROM, %7d instructions, %4d UART bytes out, %2d in, "
                "%2d traps"
                % (test.name, isa, 4 * len(image.words), model.retired, len(out),
                   len(test.console_input), len(model.traps))
            )  # fmt: skip
        check_builds_agree(test, outputs)
    vec.write(project.path(VECTOR_FILE))
    return summary


def main(argv: Sequence[str] | None = None) -> int:
    """Generate the C software tests; returns the exit status."""
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    cli.add_common_arguments(parser)
    args = parser.parse_args(argv)
    project = cli.project_from(args)

    print("\n".join(generate(project, find_toolchain(project.root))))
    return 0


if __name__ == "__main__":
    sys.exit(cli.run(main, "gen_sw_tests"))
