#!/usr/bin/env python3
"""Exhaustive decompressor vectors from the GNU toolchain (Phase 11).

Writes vectors/decompressor_vectors.txt: every 16-bit encoding with
instr[1:0] != 11 (49152 of them), its 32-bit expansion and the illegal flag.

The oracle is independent of the RTL and of the Python model:
  1. riscv-none-elf-as places every encoding with .insn and
     riscv-none-elf-objdump -M no-aliases decodes it for rv32imc_zicsr;
  2. each decoded c.* instruction is rewritten as its RV32I expansion from the
     table in the RISC-V specification (operands are taken verbatim from
     objdump, so immediates and register fields are decoded by binutils);
  3. riscv-none-elf-as assembles the expansions without the C extension.
objdump accepts a few encodings that the specification reserves; the
RESERVED rules below mark them illegal. An illegal encoding expands to
00000000, the word main_control_unit decodes as illegal.

Usage:  python3 sw/gen_decompressor_vectors.py [--prefix riscv-none-elf-] [--root DIR]
The prefix may include a directory; by default the toolchain is found as for
every tool (TIMUR_TOOLCHAIN_PREFIX, PATH, .tools/xpack-*/bin).
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from collections.abc import Callable, Sequence
from pathlib import Path

from timur_tools import cli, paths, romimage
from timur_tools.errors import GenerationError
from timur_tools.paths import Project
from timur_tools.rvc import ILLEGAL, is_compressed
from timur_tools.toolchain import Toolchain, require_toolchain

VECTOR_FILE = paths.VECTORS + "/decompressor_vectors.txt"
ENCODINGS = [value for value in range(0x10000) if is_compressed(value)]
#: objdump mnemonics of encodings that are not instructions.
NOT_INSTRUCTIONS = (".insn", "c.unimp")

_DUMP_LINE = re.compile(r"\s*([0-9a-f]+):\s+([0-9a-f]{4})\s+(\S+)\s*(.*)")
_WORD_LINE = re.compile(r"^\s*[0-9a-f]+:\s+([0-9a-f]{8})\s", re.MULTILINE)

HEADER = [
    "// decompressor test vectors, generated by sw/gen_decompressor_vectors.py from the GNU",
    "// toolchain (binutils decodes every encoding, the expansions are assembled without C).",
    "// format: instr16(hex) instr32(hex) illegal(bin); every encoding with instr[1:0] != 11.",
    "// Illegal and reserved encodings expand to 00000000 (decoded as illegal).",
]


def reserved(value: int) -> bool:
    """Encodings objdump decodes but the specification reserves (or leaves to
    custom extensions on RV32); Timur treats them as illegal."""
    quadrant, funct3 = value & 3, value >> 13
    if quadrant == 1 and funct3 == 3 and ((value >> 7) & 31) == 2:  # C.ADDI16SP, nzimm = 0
        nzimm = (
            ((value >> 12) & 1) << 9
            | ((value >> 3) & 3) << 7
            | ((value >> 5) & 1) << 6
            | ((value >> 2) & 1) << 5
            | ((value >> 6) & 1) << 4
        )
        if nzimm == 0:
            return True
    if quadrant == 1 and funct3 == 4 and ((value >> 10) & 3) in (0, 1) and (value >> 12) & 1:
        return True  # C.SRLI/C.SRAI with shamt[5] set
    return bool(quadrant == 2 and funct3 == 0 and (value >> 12) & 1)  # C.SLLI shamt[5]


def expansion(mnemonic: str, operand_text: str, address: int) -> str | None:
    """RV32I assembly text for a decoded compressed instruction, or None if there
    is no rule for the mnemonic."""
    ops = [operand.strip() for operand in operand_text.split(",")] if operand_text else []

    def offset(target: str) -> str:  # objdump prints branch and jump targets as addresses
        return ".%+d" % (int(target.split()[0], 16) - address)

    rules: dict[str, Callable[[], str]] = {
        "c.addi4spn": lambda: "addi %s,%s,%s" % (ops[0], ops[1], ops[2]),
        "c.lw": lambda: "lw %s,%s" % (ops[0], ops[1]),
        "c.sw": lambda: "sw %s,%s" % (ops[0], ops[1]),
        "c.nop": lambda: "addi zero,zero,0",
        "c.addi": lambda: "addi %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.jal": lambda: "jal ra,%s" % offset(ops[0]),
        "c.li": lambda: "addi %s,zero,%s" % (ops[0], ops[1]),
        "c.addi16sp": lambda: "addi sp,sp,%s" % ops[1],
        "c.lui": lambda: "lui %s,%s" % (ops[0], ops[1]),
        "c.srli": lambda: "srli %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.srli64": lambda: "srli %s,%s,0" % (ops[0], ops[0]),
        "c.srai": lambda: "srai %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.srai64": lambda: "srai %s,%s,0" % (ops[0], ops[0]),
        "c.andi": lambda: "andi %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.sub": lambda: "sub %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.xor": lambda: "xor %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.or": lambda: "or %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.and": lambda: "and %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.j": lambda: "jal zero,%s" % offset(ops[0]),
        "c.beqz": lambda: "beq %s,zero,%s" % (ops[0], offset(ops[1])),
        "c.bnez": lambda: "bne %s,zero,%s" % (ops[0], offset(ops[1])),
        "c.slli": lambda: "slli %s,%s,%s" % (ops[0], ops[0], ops[1]),
        "c.slli64": lambda: "slli %s,%s,0" % (ops[0], ops[0]),
        "c.lwsp": lambda: "lw %s,%s" % (ops[0], ops[1]),
        "c.swsp": lambda: "sw %s,%s" % (ops[0], ops[1]),
        "c.jr": lambda: "jalr zero,0(%s)" % ops[0],
        "c.mv": lambda: "add %s,zero,%s" % (ops[0], ops[1]),
        "c.ebreak": lambda: "ebreak",
        "c.jalr": lambda: "jalr ra,0(%s)" % ops[0],
        "c.add": lambda: "add %s,%s,%s" % (ops[0], ops[0], ops[1]),
    }
    rule = rules.get(mnemonic)
    return rule() if rule else None


def decode_all(toolchain: Toolchain, work: Path) -> dict[int, tuple[int, str, str]]:
    """{encoding: (address, mnemonic, operands)} as objdump decodes each encoding."""
    source, obj = work / "c.s", work / "c.o"
    lines = [".option rvc"] + [".insn 2, 0x%04x" % value for value in ENCODINGS]
    romimage.write_lines(source, lines)
    toolchain.run("as", "-march=rv32imc_zicsr", "-o", obj, source)
    decoded = {}
    for line in toolchain.run("objdump", "-d", "-M", "no-aliases", obj).splitlines():
        match = _DUMP_LINE.match(line)
        if match:
            address, word = int(match.group(1), 16), int(match.group(2), 16)
            decoded[word] = (address, match.group(3), match.group(4).split("#")[0].strip())
    if len(decoded) != len(ENCODINGS):
        raise GenerationError("objdump decoded %d of %d encodings" % (len(decoded), len(ENCODINGS)))
    return decoded


def assemble_expansions(toolchain: Toolchain, work: Path, texts: dict[int, str]) -> dict[int, int]:
    """{encoding: 32-bit word} of the expansions, assembled without the C extension."""
    order = sorted(texts)
    source, obj = work / "x.s", work / "x.o"
    romimage.write_lines(source, [".option norvc"] + [texts[value] for value in order])
    toolchain.run("as", "-march=rv32im_zicsr", "-o", obj, source)
    words = [int(word, 16) for word in _WORD_LINE.findall(toolchain.run("objdump", "-d", obj))]
    if len(words) != len(order):
        raise GenerationError("expansions: %d words for %d instructions" % (len(words), len(order)))
    return dict(zip(order, words, strict=True))


def generate(project: Project, toolchain: Toolchain) -> tuple[int, int]:
    """Write the vector file; returns (legal, illegal) encoding counts."""
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        decoded = decode_all(toolchain, work)
        texts = {}
        for value in ENCODINGS:
            address, mnemonic, operands = decoded[value]
            if mnemonic in NOT_INSTRUCTIONS or reserved(value):
                continue
            text = expansion(mnemonic, operands, address)
            if text is None:
                raise GenerationError(
                    "no expansion rule for %04X: %s %s" % (value, mnemonic, operands)
                )
            texts[value] = text
        expanded = assemble_expansions(toolchain, work, texts)
    lines = HEADER + [
        "%04X %08X %d" % (value, expanded.get(value, ILLEGAL), 0 if value in texts else 1)
        for value in ENCODINGS
    ]
    romimage.write_lines(project.path(VECTOR_FILE), lines)
    return len(texts), len(ENCODINGS) - len(texts)


def main(argv: Sequence[str] | None = None) -> int:
    """Generate the decompressor vectors; returns the exit status."""
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    parser.add_argument("--prefix", help="tool prefix, for example /opt/riscv/bin/riscv-none-elf-")
    cli.add_common_arguments(parser)
    args = parser.parse_args(argv)
    project = cli.project_from(args)

    legal, illegal = generate(project, require_toolchain(project.root, args.prefix))
    print("%d encodings, %d legal, %d illegal" % (legal + illegal, legal, illegal))
    return 0


if __name__ == "__main__":
    sys.exit(cli.run(main, "gen_decompressor_vectors"))
