#!/usr/bin/env python3
"""Timur C software tests (Phase 12): build, run on the reference model, write the vectors.

Builds every program in sw/tests/ for rv32im_zicsr and rv32imc_zicsr with the
runtime (sw/build.py), runs each image on the reference model of
sw/gen_soc_tests.py with interrupts and the console input modelled, checks
the result, and writes, relative to the project root (run it from there):
  vectors/timur_sw_<name>_<isa>.hex   ROM image, 32-bit words, symbols as comments
  vectors/timur_sw_<name>_<isa>.out   UART output of the model: what tb/timur_sw_tb.v expects
  vectors/timur_sw_<name>.in          UART input, for programs that read the console
  vectors/timur_sw_vectors.txt        programs and checks for tb/timur_sw_tb.v

The model sends UART bytes at once and copies DMA blocks at once, so it takes
interrupts earlier than the SoC does; the programs print nothing that depends
on timing, which is why their output must match the SoC's byte for byte. The
generator also checks that the two builds print the same text (the traps test
up to its final report, which shows a code address) and that each program's
own checks passed on the model.

Without the toolchain the committed images are read back, so the expectations
can still be regenerated. Usage:  python3 sw/gen_sw_tests.py
"""

import os
import re
import sys
import tempfile

import build
import gen_soc_tests as soc

ISAS = ("rv32im_zicsr", "rv32imc_zicsr")
UART_BIT = 16            # tb/timur_sw_tb.v: UART_DIVIDER = 15
SYMBOLS = ("_start", "_halt", "trap_entry", "main", "_end", "_heap_end", "_stack_top")
BAD_WORDS = ("MISMATCH", "DIFFER", "WRONG", "not reached", "FAIL")

# name, what it covers, console input, text the output must contain, LEDs at the end,
# text after which the two builds may differ, HREADY-wait runs
TESTS = [
    ("hello", "printf, a CSR read, the switches", b"",
     ["Hello from Timur RV32IMC!", "misa 40001104: RV32IMC"], 0x200, None, False),
    ("selftest", "globals and sections, stack and recursion, arithmetic including division by zero, "
     "the C library, the heap up to exhaustion, ECALL system calls, CSRs", b"",
     ["checks passed"], 0x200, None, True),
    ("traps", "exceptions handled by the program (illegal instruction, EBREAK, misaligned loads and "
     "stores, 16- and 32-bit), then the runtime's report of an unhandled one", b"",
     ["10 exceptions handled;", "reaches the system calls: yes", "*** unhandled trap: illegal instruction"],
     0x302, "*** unhandled trap", False),
    ("io", "console input with fgets, sscanf and getchar; DMA done interrupt, a masked interrupt "
     "taken once MIE is set, UART receive interrupt", b"12 -30\rTimur\rstressed\rinterrupts work\r",
     ["copied from ROM to RAM correctly", "mip.MEIP = 1", "copy correct", "16 bytes, 16 receive interrupts"],
     0x200, None, False),
]


def image_path(name, isa):
    return "vectors/timur_sw_%s_%s.hex" % (name, isa.split("_")[0])


def build_image(name, isa):
    """Build sw/tests/<name>.c; write and return (words, symbols). Without the toolchain,
    read the committed image back."""
    path = image_path(name, isa)
    if build.toolchain_prefix() is None:
        words, syms = [], {}
        for line in open(path):
            m = re.match(r"// symbol (\S+) ([0-9A-F]{8})", line)
            if m:
                syms[m.group(1)] = int(m.group(2), 16)
            elif line.strip() and not line.startswith("//"):
                words.append(int(line.split()[0], 16))
        return words, syms
    with tempfile.TemporaryDirectory() as tmp:
        r = build.build([os.path.join("sw", "tests", name + ".c")], isa, tmp, name)
    syms = {s: r["symbols"][s] for s in SYMBOLS}
    with open(path, "w") as f:
        f.write("// %s (%s): sw/tests/%s.c with the runtime, built by sw/build.py, %d bytes\n"
                % (name, isa, name, r["bytes"]))
        for s in SYMBOLS:
            f.write("// symbol %s %08X\n" % (s, syms[s]))
        for w in r["words"]:
            f.write("%08X\n" % w)
    return r["words"], syms


def run_model(words, uart_in):
    m = soc.Timur({4 * i: w for i, w in enumerate(words)}, uart_rx=uart_in, interrupts=True, trace=False)
    m.run(50000000)
    return m


def main():
    vec = soc.Vectors()
    vec.comment("timur_sw test vectors, generated by sw/gen_sw_tests.py: the C programs of Phase 12")
    vec.comment("on tb/timur_sw_tb.v (timur_soc_tb with a UART of %d cycles per bit)." % UART_BIT)
    vec.comment("Directives as in vectors/timur_soc_vectors.txt, and:")
    vec.comment("  UARTIN <file>    bytes sent on uart_rx during the next PROG, each once the receiver is")
    vec.comment("                   enabled and holds no unread byte; the PROG also checks that all were read")
    vec.comment("  UARTTEXT <file>  the bytes decoded from uart_tx equal the file (the model's output)")
    vec.comment("PROG halts at _halt, the jump-to-self that _exit ends in; LEDS is 0x200 | the exit code.")
    vec.comment("")
    summary = []
    for name, what, uart_in, must, leds, differ_after, waits in TESTS:
        if uart_in:
            with open("vectors/timur_sw_%s.in" % name, "wb") as f:
                f.write(uart_in)
        outputs = {}
        for isa in ISAS:
            words, syms = build_image(name, isa)
            m = run_model(words, uart_in)
            out = bytes(m.uart_tx)
            text = out.decode("ascii")
            if m.pc != syms["_halt"]:
                sys.exit("model: %s (%s) stopped at %08X, not at _halt" % (name, isa, m.pc))
            if m.uart_rx or m.rx_valid:
                sys.exit("model: %s (%s) left console input unread" % (name, isa))
            for s in must:
                if s not in text:
                    sys.exit("model: %s (%s) output lacks %r:\n%s" % (name, isa, s, text))
            for s in BAD_WORDS:
                if s in text:
                    sys.exit("model: %s (%s) output contains %r:\n%s" % (name, isa, s, text))
            if m.gpio_out != leds:
                sys.exit("model: %s (%s) ends with LEDs %03X, expected %03X" % (name, isa, m.gpio_out, leds))
            outputs[isa] = out
            out_path = "vectors/timur_sw_%s_%s.out" % (name, isa.split("_")[0])
            with open(out_path, "wb") as f:
                f.write(out)
            cycles = 20 * m.retired + 3 * 10 * UART_BIT * (len(out) + 3 * len(uart_in)) + 20000
            for w in ((0, 1) if waits else (0,)):
                vec.comment("==== %s (%s)%s: %s; %d instructions on the model, %d UART bytes"
                            % (name, isa, ", HREADY waits" if w else "", what, m.retired, len(out)))
                if uart_in:
                    vec.add("UARTIN vectors/timur_sw_%s.in" % name)
                vec.prog(image_path(name, isa), cycles, syms["_halt"], w)
                vec.add("UARTTEXT %s" % out_path)
                vec.add("LEDS %03X" % m.gpio_out)
                vec.add("DIVS %d" % m.divs)
            summary.append("%-9s %-14s %6d bytes of ROM, %7d instructions, %4d UART bytes out, %2d in, %2d traps"
                           % (name, isa, 4 * len(words), m.retired, len(out), len(uart_in), len(m.traps)))
        a, b = (outputs[isa] for isa in ISAS)
        if differ_after:
            a, b = a.split(differ_after.encode())[0], b.split(differ_after.encode())[0]
        if a != b:
            sys.exit("model: %s prints different text for %s and %s" % (name, *ISAS))
    with open("vectors/timur_sw_vectors.txt", "w") as f:
        f.write("\n".join(vec.lines) + "\n")
    print("\n".join(summary))


if __name__ == "__main__":
    main()
